---
title: "viz2"
author: "Ye Dam Yi"
date: "4/14/2021"
output: html_document
---
```{r libraries}
require(tidyverse)
require(haven)

```


```{r read-data}
risk_all <- read_spss("/Users/yedam/Documents/GitHub/DSP/Project/project7-emotion-risk/data/risk_excluded.sav")
risk_sur <- read_spss("/Users/yedam/Documents/GitHub/DSP/Project/project7-emotion-risk/data/risk_sur.sav")
risk_pred <- read_spss("/Users/yedam/Documents/GitHub/DSP/Project/project7-emotion-risk/data/risk_pred.sav")

write_sav(risk_all, "data/risk_all.sav")
write_sav(risk_sur, "data/risk_sur.sav")
write_sav(risk_pred, "data/risk_pred.sav")


risk_all <- risk_all %>% 
  mutate(gender = as_factor(gender),
         condition = as_factor(condition),
         rel_self = as_factor(rel_self),
         rel_friend1 = as_factor(rel_friend1),
         rel_friend2 = as_factor(rel_friend2)) 

```

```{r recode}
risk_all <- risk_all %>% 
  mutate(risklevel = case_when(risklevel == 0 ~ 1,
                               risklevel == 1 ~ 2,
                               risklevel == 2 ~ 3,
                               risklevel == 3 ~ 4,
                               risklevel == 4 ~ 5,
                               risklevel == 5 ~ 6,
                               risklevel == 6 ~7),
         neg = case_when(neg == 0 ~ 1,
                         neg == 1 ~ 2,
                         neg == 2 ~ 3,
                         neg == 3 ~ 4,
                         neg == 4 ~ 5),
         pos = case_when(pos == 0 ~ 1,
                         pos == 1 ~ 2,
                         pos == 2 ~ 3,
                         pos == 3 ~ 4,
                         pos == 4 ~ 5),
         alert = case_when(alert == 0 ~ 1,
                         alert == 1 ~ 2,
                         alert == 2 ~ 3,
                         alert == 3 ~ 4,
                         alert == 4 ~ 5),
         riskyrisk = case_when(riskyrisk == 0 ~ 1,
                         riskyrisk == 1 ~ 2,
                         riskyrisk == 2 ~ 3,
                         riskyrisk == 3 ~ 4,
                         riskyrisk == 4 ~ 5),
         riskavrisk = case_when(riskavrisk == 0 ~ 1,
                         riskavrisk == 1 ~ 2,
                         riskavrisk == 2 ~ 3,
                         riskavrisk == 3 ~ 4,
                         riskavrisk == 4 ~ 5))

summary(risk_all)
```

```{r theme}

mytheme = theme(
  axis.title.x = element_text(size = 22),
  axis.text.x = element_text(size = 20),
  axis.title.y = element_text(size = 22),
  axis.ticks.length=unit(.25, "cm"),
  axis.text = element_text(size = 18)
)

```

```{r manipulation, fig.height=2, fig.width=3}
jpeg("manipulationcheck.jpg", width = 500, height = 380)

risk_all %>% 
  pivot_longer(c(riskyrisk, riskavrisk), names_to = "option", values_to = "riskrating") %>% 
  group_by(option) %>% 
  summarise(
    mean = mean(riskrating),
    sd = sd(riskrating)
  ) %>% 
  ggplot(aes(x = option, y = mean)) +
  geom_bar(stat = "identity", fill = "grey", position=position_dodge(), width = .5) +  
  geom_errorbar(aes(ymin= mean-sd, ymax = mean + sd),  width=.15, position=position_dodge(.9)) +
  labs(x = "",
       y = "Riskiness") +
  scale_x_discrete(labels = c("Stay with Friends", "Approach Barista")) +
      coord_cartesian(ylim=c(0, 5)) +
  theme_classic() +
  mytheme

# Hadley explains this on pp. 99; 133 of his ggplot2 book (1st edition), or pp. 160 - 161 if you have the second edition.
# 
# The issue is that, as you say, limits inside the scale or setting ylim() causes data to be thrown away, as they are constraining the data. For a true zoom (keep all the data), you need to set the limits inside of the Cartesian coordinate system (or other coordinate systems https://ggplot2.tidyverse.org/reference/#section-coordinate-systems). For more see: http://docs.ggplot2.org/current/coord_cartesian.html

dev.off()



```

```{r data-manipulation}
df <- risk_all %>% 
  group_by(condition) %>% 
  summarise(
    mean_risk = mean(risklevel),
    sd_risk = sd(risklevel),
    mean_neg = mean(neg),
    sd_neg = sd(neg),
    mean_pos = mean(pos),
    sd_pos = sd(pos),
    mean_alert = mean(alert),
    sd_alert = sd(alert)
  )
df
```
```{r risklevels}
jpeg("rt_bar.jpg", width = 500, height = 380)

df %>% 
  ggplot(aes(y = mean_risk, x = condition)) +
  geom_bar(stat = "identity", fill = "grey", position=position_dodge(), width = .5) +
  geom_errorbar(aes(ymin = mean_risk - sd_risk, ymax = mean_risk + sd_risk),  width=.15, position=position_dodge(.9)) +
  labs(x = "",
       y = "Risk Taking Levels") +
  scale_x_discrete(labels = c("Self", "Surrogate", "Prediction")) +
  coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = c(1,2,3,4,5,6,7)) +
  theme_classic() +
  mytheme

dev.off()

```

```{r neg}
jpeg("neg_bar.jpg", width = 500, height = 380)

df %>% 
  ggplot(aes(y = mean_neg, x = condition)) +
  geom_bar(stat = "identity", fill = "grey",position=position_dodge(), width = .5) +
  geom_errorbar(aes(ymin = mean_neg - sd_neg, ymax = mean_neg + sd_neg),  width=.15, position=position_dodge(.9)) +
  labs(x = "",
       y = "Negative Emotion") +
  scale_x_discrete(labels = c("Self", "Surrogate", "Prediction")) +
coord_cartesian(ylim = c(1,5)) +
  scale_y_continuous(breaks = c(1,2,3,4,5)) +  theme_classic() +
  mytheme

dev.off()

```

```{r pos}
jpeg("pos_bar.jpg", width = 500, height = 380)

df %>% 
  ggplot(aes(y = mean_pos, x = condition)) +
  geom_bar(stat = "identity", fill = "grey",position=position_dodge(), width = .5) +
  geom_errorbar(aes(ymin = mean_pos - sd_pos, ymax = mean_pos + sd_pos), width=.15, position=position_dodge(.9)) +
  labs(x = "",
       y = "Positive Emotion") +
  scale_x_discrete(labels = c("Self", "Surrogate", "Prediction")) +
  coord_cartesian(ylim = c(1,5)) +
  scale_y_continuous(breaks = c(1,2,3,4,5)) +
  theme_classic() +
  mytheme

dev.off()

```

```{r alert}
jpeg("alert_bar.jpg", width = 500, height = 380)

df %>% 
  ggplot(aes(y = mean_alert, x = condition)) +
  geom_bar(stat = "identity", fill = "grey", position=position_dodge(), width = .5) +
  geom_errorbar(aes(ymin = mean_alert - sd_alert, ymax = mean_alert + sd_alert), width=.15, position=position_dodge(.9)) +
  labs(x = "",
       y = "Alertness") +
  scale_x_discrete(labels = c("Self", "Surrogate", "Prediction")) +
    coord_cartesian(ylim = c(1,5)) +
  scale_y_continuous(breaks = c(1,2,3,4,5)) +
  theme_classic() +
  mytheme

dev.off()

```